---@meta
---Brightness (Value) of the Color tones.
---@class EColorShade
---@field public DarkMinus EColorShade [0]
---@field public DarkBase EColorShade [1]
---@field public DarkPlus EColorShade [2]
---@field public MidMinus EColorShade [3]
---@field public MidBase EColorShade [4]
---@field public MidPlus EColorShade [5]
---@field public LightMinus EColorShade [6]
---@field public LightBase EColorShade [7]
---@field public LightPlus EColorShade [8]
---@field public NUM EColorShade [9]
EColorShade = {}
