---@class EPropertySlotType
---@field public None EPropertySlotType [0]
---@field public CheckBox EPropertySlotType [1]
---@field public ProgressBar EPropertySlotType [2]
---@field public Slider EPropertySlotType [3] //Read-only, 0..1 value range
---@field public SpinBox EPropertySlotType [4]
---@field public ComboBox EPropertySlotType [5]
---@field public TextBox EPropertySlotType [6]
---@field public InputKeySelector EPropertySlotType [7]
---@field public SliderSpin EPropertySlotType [8]
---@field public Vector2D EPropertySlotType [9]
---@field public Vector EPropertySlotType [10]
---@field public Color EPropertySlotType [11] 3D
---@field public Custom EPropertySlotType [12] Color preview with the Color Picker opening feature
---@field public TextBlock EPropertySlotType [13] Fully custom, see UPropertySlotStyle_Custom for more details
EPropertySlotType = {}
