---Represents the appearance of an SSpinBox
---@class FSpinBoxStyle : FSlateWidgetStyle
---@field public BackgroundBrush FSlateBrush @Brush used to draw the background of the spinbox
---@field public ActiveBackgroundBrush FSlateBrush
---@field public HoveredBackgroundBrush FSlateBrush @Brush used to draw the background of the spinbox when it's hovered over
---@field public ActiveFillBrush FSlateBrush @Brush used to fill the spinbox when it's active
---@field public HoveredFillBrush FSlateBrush @Brush used to fill the spinbox when it's hovered and not active
---@field public InactiveFillBrush FSlateBrush @Brush used to fill the spinbox when it's inactive
---@field public ArrowsImage FSlateBrush @Image used to draw the spinbox arrows
---@field public ForegroundColor FSlateColor @Color used to draw the spinbox foreground elements
---@field public TextPadding FMargin @Padding to add around the spinbox and its text
---@field public InsetPadding FMargin @Padding between the background brush and the fill brush
FSpinBoxStyle = {}
